DROP TABLE IF exists endpoints_hit CASCADE;
CREATE TABLE IF NOT EXISTS endpoints_hit (
                               id BIGINT generated by default as identity not null ,
                               app varchar(255),
                               uri varchar(255),
                               ip varchar(255),
                               timestamp timestamp,
                               CONSTRAINT pk_endpoints primary key (id)
)